- name: install nginx
  hosts: 172.31.31.156
  #hosts: all
  become: yes
  serial: 3
  # vars_files:
  #   - /var/credentials.yaml
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes