  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: start mysql service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect my sql server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{login_password}}"
      login_host: "{{login_host}}"
    ignore_errors: true
    register: sql_info

  - name: get db info
    ansible.builtin.debug:
      msg: "{{sql_info}}"

  - name: setup Mysql root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{login_password}}"
    when: sql_info.failed is true